[global]
type=global
user_agent=Asterisk-PBX
endpoint_identifier_order=ip,username

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_signaling_address=155.138.246.27
external_media_address=155.138.246.27
; This allows Asterisk to talk to any IP range
local_net=0.0.0.0/0

[telnyx-auth]
type=auth
auth_type=userpass
username=useradmin75672
password=gPF^I=9JZ8nb

[telnyx-aor]
type=aor
contact=sip:sip.telnyx.com:5060

[telnyx-endpoint]
type=endpoint
context=from-telnyx
disallow=all
allow=ulaw,alaw
aors=telnyx-aor
outbound_auth=telnyx-auth
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
direct_media=no

[telnyx-identify]
type=identify
endpoint=telnyx-endpoint
match=192.76.120.0/24
match=192.76.121.0/24

[telnyx-reg]
type=registration
transport=transport-udp
outbound_auth=telnyx-auth
server_uri=sip:sip.telnyx.com:5060
client_uri=sip:useradmin75672@sip.telnyx.com
line=yes
endpoint=telnyx-endpoint
contact_user=s
